sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t siyandav0/react-test -f ../client/Dockerfile.dev ../client

script:
  - docker run -e CI=true siyandav0/react-test npm test

after_success:
  - docker build -t siyandav0/multi-client ../client
  - docker build -t siyandav0/multi-nginx ../nginx
  - docker build -t siyandav0/multi-server ../server
  - docker build -t siyandav0/multi-worker ../worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push siyandav0/multi-client
  - docker push siyandav0/multi-nginx
  - docker push siyandav0/multi-server
  - docker push siyandav0/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'multi-docker'
#   env: 'Multidocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-579929968227'
#   bucket_path: 'docker-multi'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
